/**
 * Author: Bharat Singh
 */
package com.cg.cba.entities;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;

import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

//creating a table in the database
@Entity
@Table

//using Lombok api to generate setters and getters
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@ApiModel
public class Driver extends AbstractUser{

	//*********creating columns for the database and providing notes for swagger api *******//
	
	//Making "driverId as primary key and auto incrementing it
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@ApiModelProperty(notes = "driverId will be autogenerated", required = false)
	@Pattern(regexp = "[0-9]" , message = "Enter the valid driverId")
	@Column(nullable =false)
	private int driverId;

	@Column(unique = true, nullable = false)
	@ApiModelProperty(notes = "licenseNo can not be null or blank", example = "KA05EP2489", required = true)
	@Pattern(regexp = "[A-Za-z0-9]{15}", message = "Enter the valid licenseNo")
	private String licenseNo;

	//implementing Has a relationship of Cab Class and implementing one to one relationship
	@OneToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL, orphanRemoval = true)
	private Cab cab;

	@ApiModelProperty(required = true, example = "4.5")
	@NotNull
	@Column
	@Pattern(regexp = "^[0-9]{0,1}.?[0-9]{1}$*" , message = "Provide the  valid rating ")
	private float rating;

}